stages:
  - docs
  - build

readme:
 tags:
   - getflow
 stage: docs
 image:
   name: chko/docker-pushrm
   entrypoint: ["/bin/sh", "-c", "/docker-pushrm"]
 variables:
   DOCKER_USER: $DOCKER_HUB_USER
   DOCKER_PASS: $DOCKER_HUB_KEY
   PUSHRM_SHORT: Image with cloudflared preinstalled and ssh configured
   PUSHRM_TARGET: docker.io/getflow/cloudflared-ssh
   PUSHRM_FILE: $CI_PROJECT_DIR/README.md
 script: "/bin/true"


build-debian:
  tags:
    - getflow
  stage: build
  image: docker:latest
  before_script:
    - echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
  script:
    - docker build -t getflow/cloudflared-ssh:latest -t getflow/cloudflared-ssh:debian .
    - docker push getflow/cloudflared-ssh:latest getflow/cloudflared-ssh:debian
  after_script:
    - docker rmi getflow/cloudflared-ssh:latest getflow/cloudflared-ssh:debian
    - docker logout

build-docker:
  tags:
    - getflow
  stage: build
  image: docker:latest
  before_script:
    - echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
  script:
    - docker build -t getflow/cloudflared-ssh:docker --build-arg BASE_IMAGE=docker .
    - docker push getflow/cloudflared-ssh:docker
  after_script:
    - docker rmi getflow/cloudflared-ssh:docker
    - docker logout
