stages:
  - build

build:
  tags:
    - getflow
  stage: build
  image: docker:latest
  before_script:
    - echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
  script:
    - docker build -t getflow/cloudflared-ssh:latest .
    - docker push getflow/cloudflared-ssh:latest 
  after_script:
    - docker rmi getflow/cloudflared-ssh:latest
    - docker logout

