stages:
  - docs
  - build

readme:
 tags:
   - getflow
 stage: docs
 image:
   name: chko/docker-pushrm
   entrypoint: ["/bin/sh", "-c", "/docker-pushrm"]
 variables:
   DOCKER_USER: $DOCKER_HUB_USER
   DOCKER_PASS: $DOCKER_HUB_KEY
   PUSHRM_SHORT: Image with cloudflared preinstalled and ssh configured for connecting to SSH endpoints behind Cloudflare
   PUSHRM_TARGET: docker.io/getflow/cloudflared-ssh
   PUSHRM_FILE: $CI_PROJECT_DIR/README.md
 script: "/bin/true"


build:
  tags:
    - getflow
  stage: build
  image: docker:latest
  before_script:
    - echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
  script:
    - docker build -t getflow/cloudflared-ssh:latest .
    - docker push getflow/cloudflared-ssh:latest 
  after_script:
    - docker rmi getflow/cloudflared-ssh:latest
    - docker logout

